(()=>{
'use strict';
const $=id=>document.getElementById(id),E=OneSecond,now=()=>performance.timeOrigin+performance.now();
const C=GAME_CONFIG||{},url=(C.serverUrl||'').replace(/\/$/,'');
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const settings=load('one-second-settings',{step:20,sound:false});let name=load('one-second-name','Guest');let screen='menu',mode='local',difficulty='normal',g,state,peer,host=false,you=0,names=['Player 1','Player 2'],roomId='',botStart,botAt,botMoveAt,lastBoard='',lastStatus='',lastMiss=[0,0],toastTimer;
const cells=Array.from({length:9},(_,i)=>{let b=document.createElement('button');b.className='cell';b.onclick=()=>place(i);$('board').append(b);return b});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500)}
function view(v){screen=v;['menu','lobbies','room','game'].forEach(x=>$(x).hidden=x!==v);$('profile').textContent=name+' ✎'}
function modal(t,h){$('modal-label').textContent=t;$('modal-body').innerHTML=h;$('dialog').showModal()}function close(){if($('dialog').open)$('dialog').close()}$('close-dialog').onclick=close;
function reset(){lastBoard='';lastStatus='';lastMiss=[0,0];botStart=botMoveAt=null;$('again').hidden=true;cells.forEach(b=>{b.replaceChildren();delete b.dataset.value;b.classList.remove('winning')})}
function startLocal(m){mode=m;g=new E.Match({now:now(),step:settings.step});state=g.snapshot();names=m==='local'?['Player 1','Player 2']:[name,'Bot'];you=0;peer=null;reset();view('game');render()}
function send(x){peer?.send(x)}
function openPlay(){view('lobbies');$('lobby-message').textContent='Connecting…';peer=new LobbyConnection({serverUrl:url,name});peer.onList=rooms=>{let el=$('lobby-list');el.innerHTML=rooms.length?rooms.map(r=>`<button class="lobby-entry" data-id="${r.id}"><span><b>${esc(r.host)}</b><small>${r.id} · ${r.settings.step/1000}s</small></span><span>Join ↗</span></button>`).join(''):'<p>No open lobbies yet. Create one.</p>';el.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>send({type:'join',id:b.dataset.id}))};peer.onRoom=(r,h)=>{host=h;roomId=r.id;roomUI(r);view('room')};peer.onStart=m=>{mode='peer';host=peer.host;roomId=m.matchId;names=host?[name,m.room.guest]:[m.room.host,name];you=host?m.room.settings.hostMark:1-m.room.settings.hostMark;g=host?new E.Match({now:now(),step:m.room.settings.step,online:true,moveSeconds:m.room.settings.moveSeconds}):null;state=host?g.snapshot():null;reset();view('game');if(host)broadcast()};peer.onData=m=>{if(host)return;if(m.type==='state'){state=m.state;render()}if(m.type==='finish'){state={...state,phase:'ended',result:m.result};render()}};peer.onFinished=m=>{state={...state,phase:'ended',result:{winner:m.winner,reason:m.reason,line:[]}};render()};peer.onError=toast;peer.onClosed=()=>{view('lobbies');toast('Lobby closed')};peer.onPeerLeft=()=>toast('Rival left');peer.onDisconnect=()=>toast('Connection lost');peer.connect().catch(e=>{toast(e.message);view('menu')})}
function roomUI(r){$('room-id').textContent=r.id;$('room-link').textContent=peer.transport;$('host-name').textContent=r.host;$('guest-name').textContent=r.guest||'Waiting…';$('host-symbol').textContent=r.settings.hostMark?'○':'×';$('guest-symbol').textContent=r.settings.hostMark?'×':'○';$('room-mark').value=r.settings.hostMark;$('room-time').value=r.settings.moveSeconds;document.querySelectorAll('#room-step,#room-mark,#room-time').forEach(x=>x.disabled=!host);$('start-match').disabled=!host||!r.guest||!peer.ready;$('room-status').textContent=!r.guest?'Waiting for a player…':!peer.ready?'Connecting players…':host?'Ready. Start when you are.':'Waiting for host to start…'}
function broadcast(){if(host&&state)send({type:'state',state})}
function stop(p){if(!state||!['race','deciding'].includes(state.phase)||(mode==='peer'&&p!==you))return;if(mode==='peer'&&!host){send({type:'action',action:'stop',at:now()});return}if(mode==='peer'){g.advance(now()+peer.offset);g.stop(p,now()+peer.offset);state=g.snapshot();broadcast();return}g.advance(now());g.stop(p,now());state=g.snapshot();render()}
function place(i){if(!state||state.phase!=='place')return;let p=mode==='local'?state.owner:you;if(mode==='peer'&&!host){send({type:'action',action:'place',cell:i});return}if(g.place(p,i,now())){state=g.snapshot();broadcast();render()}}
function render(){if(!state)return;$('mode-label').textContent=mode==='local'?'LOCAL':mode==='bot'?difficulty.toUpperCase()+' BOT':'PEER';$('connection').textContent=mode==='peer'?(peer?.transport||'Relay'):'';$('name-0').textContent=names[0];$('name-1').textContent=names[1];$('step-label').textContent=(state.step/1000).toFixed(state.step===25?3:2)+'s';$('round-label').textContent='ROUND '+String(state.round).padStart(2,'0');let k=JSON.stringify(state.board);if(k!==lastBoard){lastBoard=k;state.board.forEach((v,i)=>{cells[i].replaceChildren();if(v!==null){let s=document.createElement('span');s.textContent=v?'○':'×';s.className=v?'o':'x';cells[i].append(s)}})}cells.forEach((b,i)=>{b.disabled=state.phase!=='place'||state.board[i]!==null||(mode==='peer'&&!host&&state.owner!==you);b.classList.toggle('winning',!!state.result?.line?.includes(i))});for(let i=0;i<2;i++){$('stop-'+i).disabled=!['race','deciding'].includes(state.phase)||state.candidates.some(c=>c.player===i)||(mode==='peer'&&((host?state.owner!==i:i!==you)));if(state.misses[i]!==lastMiss[i]){lastMiss[i]=state.misses[i];$('player-'+i).classList.add('miss')}}if(state.phase==='countdown')status(state.round===1?String(Math.max(1,Math.ceil((state.until-now())/1000))):'Ready');else if(state.phase==='tie')status('Draw');else if(state.phase==='place')status((state.owner?'O':'X')+' to play');else if(state.phase==='ended')status(state.result.winner===-1?'Draw':names[state.result.winner]+' wins');else if(state.phase==='interrupted')status('Disconnected');$('again').hidden=!['ended','interrupted'].includes(state.phase);if(state.phase==='ended')recordStats()}
function status(s){if(lastStatus===s)return;lastStatus=s;$('status').textContent=s}
function recordStats(){let a=load('one-second-stats',{}),key=mode==='local'?'local':mode==='bot'?'bot':'peer';a[key]??={wins:0,losses:0,draws:0};if(state._recorded)return;state._recorded=true;a[key][state.result.winner===-1?'draws':state.result.winner===you?'wins':'losses']++;save('one-second-stats',a);if(mode==='peer'&&host)peer.emit({type:'result',matchId,winner:state.result.winner,reason:state.result.reason||'board'});if(mode==='bot')fetch(url+'/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),name,difficulty,winner:state.result.winner,reason:state.result.reason||'board'})}).catch(()=>{})}
function tick(){if(screen==='game'&&state){let t=now()+(mode==='peer'?(peer?.offset||0):0);if(g){let r=g.revision;g.advance(t);if(mode==='bot'){if(['race','deciding'].includes(g.phase)){if(botStart!==g.starts[1]){botStart=g.starts[1];botAt=botStart+E.botDelay(difficulty,g.step)}if(t>=botAt){g.stop(1,botAt,t);botStart=null}}if(g.phase==='place'&&g.owner===1){if(!botMoveAt)botMoveAt=t+400+Math.random()*350;if(t>=botMoveAt){g.place(1,E.chooseCell(g.board,1,difficulty),t);botMoveAt=0}}}if(g.revision!==r){state=g.snapshot();render()}}for(let i=0;i<2;i++){let ms=['race','deciding'].includes(state.phase)?(state.candidates.some(c=>c.player===i)?1000:E.value(t-state.starts[i],state.step)):state.frozen[i];$('timer-'+i).textContent=(Math.min(ms,999990)/1000).toFixed(state.step===25?3:2);$('meter-'+i).style.transform=`scaleX(${Math.min(1,ms/1000)})`}}requestAnimationFrame(tick)}
for(let i=0;i<2;i++)$('stop-'+i).onpointerdown=e=>{e.preventDefault();stop(i)};onkeydown=e=>{if(e.repeat||$('dialog').open||screen!=='game')return;if(e.key.toLowerCase()==='a')stop(mode==='local'?0:you);if(e.key.toLowerCase()==='l'&&mode==='local')stop(1);if(e.code==='Space')stop(mode==='local'?0:you)};
$('local').onclick=()=>startLocal('local');$('bot-menu').onclick=()=>{modal('SOLO','<h2>Choose your pace.</h2>'+['easy','normal','hard'].map(d=>`<button class="choice" data-d="${d}">${d}</button>`).join(''));document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.d;close();startLocal('bot')})};$('online').onclick=openPlay;$('refresh').onclick=()=>peer?.emit({type:'list'});$('create-lobby').onclick=()=>{namePrompt(()=>send({type:'create'}))};$('lobby-back').onclick=()=>{peer?.close();view('menu')};$('room-back').onclick=()=>{send({type:'leave'});view('lobbies')};$('start-match').onclick=()=>{send({type:'settings',step:+$('room-step').value,hostMark:+$('room-mark').value,moveSeconds:+$('room-time').value});send({type:'link-ready',ready:true});setTimeout(()=>send({type:'start'}),300)};$('leave').onclick=()=>{peer?.close();view('menu')};$('again').onclick=()=>mode==='peer'?view('lobbies'):startLocal(mode);$('home').onclick=()=>view('menu');$('profile').onclick=()=>namePrompt();
function namePrompt(done){modal('PLAYER NAME',`<h2>Who are you?</h2><input id="name-input" maxlength="12" value="${esc(name)}"><div class="form-error" id="name-error"></div><button class="primary" id="save-name">Save</button>`);$('save-name').onclick=()=>{let v=$('name-input').value.trim();if(!/^[A-Za-z0-9]{3,12}$/.test(v))return $('name-error').textContent='Use 3–12 letters or numbers.';name=v;save('one-second-name',name);close();if(done)done()}}
$('settings').onclick=()=>{modal('SETTINGS',`<h2>Find your rhythm.</h2><label>Timer<select id="step-setting">${E.STEPS.map(v=>`<option value="${v}">${v/1000}s</option>`).join('')}</select></label>`);$('step-setting').onchange=e=>{settings.step=+e.target.value;save('one-second-settings',settings)}};$('how').onclick=()=>modal('HOW TO PLAY','<h2>Make your second count.</h2><ol class="rules"><li>Stop at exactly 1.00s.</li><li>Hit first to place your mark.</li><li>Three in a row wins.</li></ol>');$('stats').onclick=()=>{let a=load('one-second-stats',{}),s=a.bot||{wins:0,losses:0,draws:0},g=s.wins+s.losses+s.draws;modal('STATS',`<h2>Your numbers.</h2><p>Saved on this device.</p><div class="stat-grid"><div><b>${s.wins}</b><small>BOT WINS</small></div><div><b>${s.losses}</b><small>BOT LOSSES</small></div><div><b>${g?(100*s.wins/g).toFixed(1):0}%</b><small>BOT WIN RATE</small></div></div><p class="muted">Peer: ${(a.peer?.wins||0)} wins · ${(a.peer?.losses||0)} losses · ${(a.peer?.draws||0)} draws</p><button class="danger" id="reset-stats">Reset stats</button>`);$('reset-stats').onclick=()=>{save('one-second-stats',{});close();toast('Stats reset')}};
setInterval(()=>{if(peer&&host&&!peer.onAction)peer.onAction=m=>{if(!g)return;const t=now()+peer.offset;g.advance(t);if(m.action==='stop')g.stop(1-you,t);if(m.action==='place')g.place(1-you,m.cell,t);state=g.snapshot();broadcast();render()}},100);
view('menu');$('profile').textContent=name+' ✎';tick();
})();
